# Basic
title: 晓岳晨峰
subtitle: Tech blog just for development
welcome_message: A ruby developer from living and eating in Chengdu, China. Creating the future in digital worlds, big and small at Jinshuju.net
description: Apple, Soccer, Vim and Ruby
creator: <a href="http://xfyuan.github.io">@xfyuan</a>

url: "http://xfyuan.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: orange

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Jinshuju, description: 金数据, url: 'https://www.jinshuju.net'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: xfyuan
    # duoshuo:

# Social
social:
    weibo: 昔有唐虞
    github: xfyuan
    twitter: apexy
    mail: apexy2007@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
