# Site
name: "The Tragedy of XY"
title: "The Tragedy of XY"
description: "The Tragedy of XY"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
google_analytics: ''
disqus: 'xfyuan'
mailchimp-list:
include: ["_pages"]
permalink: /:year/:month/:title/
email: apexy2007@gmail.com

# Authors
authors:
  Mr.Z:
    name: Mr.Z
    display_name: Mr.Z
    avatar: 'assets/images/avatar.png'
    gravatar: bc13037f8ea7af96ccde743e6648688f
    email: apexy2007@gmail.com
    web: https://xfyuan.github.io
    twitter: https://twitter.com/apexy
    description: "An Chinese software engineer living and working in Chengdu. I love Creating the future in digital worlds, big and small."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
